
  export default class ImageList {
      static images = [
      {name:'rule1.png',image:require('../assets/img/rule1.png')},
      {name:'rule1_1.png',image:require('../assets/img/rule1_1.png')},
      {name:'rule2.png',image:require('../assets/img/rule2.png')},
      {name:'rule3.png',image:require('../assets/img/rule3.png')},
      {name:'rule3_1.png',image:require('../assets/img/rule3_1.png')},
      {name:'rule4.png',image:require('../assets/img/rule4.png')},
      {name:'rule6.png',image:require('../assets/img/rule6.png')},
      {name:'rule7.png',image:require('../assets/img/rule7.png')},
      {name:'rule8_1.png',image:require('../assets/img/rule8_1.png')},
      {name:'rule8_2.png',image:require('../assets/img/rule8_2.png')},
      {name:'rule8_3.png',image:require('../assets/img/rule8_3.png')},
      {name:'rule10_1.png',image:require('../assets/img/rule10_1.png')},
      {name:'rule41_1.png',image:require('../assets/img/rule41_1.png')},
      {name:'rule42_1.png',image:require('../assets/img/rule42_1.png')},
      {name:'rule43_1.png',image:require('../assets/img/rule43_1.png')},
      {name:'rule49_1.png',image:require('../assets/img/rule49_1.png')},
      {name:'rule49_10.png',image:require('../assets/img/rule49_10.png')},
      {name:'rule49_11.png',image:require('../assets/img/rule49_11.png')},
      {name:'rule49_2.png',image:require('../assets/img/rule49_2.png')},
      {name:'rule49_3.png',image:require('../assets/img/rule49_3.png')},
      {name:'rule49_4.png',image:require('../assets/img/rule49_4.png')},
      {name:'rule49_5.png',image:require('../assets/img/rule49_5.png')},
      {name:'rule49_6.png',image:require('../assets/img/rule49_6.png')},
      {name:'rule49_7.png',image:require('../assets/img/rule49_7.png')},
      {name:'rule49_8.png',image:require('../assets/img/rule49_8.png')},
      {name:'rule49_9.png',image:require('../assets/img/rule49_9.png')},
      {name:'rule106_1.png',image:require('../assets/img/rule106_1.png')},
      {name:'rule118_1.png',image:require('../assets/img/rule118_1.png')},
      {name:'rule118_2.png',image:require('../assets/img/rule118_2.png')},
      {name:'rule120_1.png',image:require('../assets/img/rule120_1.png')},
      {name:'rule120_2.png',image:require('../assets/img/rule120_2.png')},
      {name:'rule120_3.png',image:require('../assets/img/rule120_3.png')},
      {name:'rule127.png',image:require('../assets/img/rule127.png')},
      {name:'rule132.png',image:require('../assets/img/rule132.png')},
      {name:'rule133_1.png',image:require('../assets/img/rule133_1.png')},
      {name:'rule133_2.png',image:require('../assets/img/rule133_2.png')},
      {name:'rule134_1.png',image:require('../assets/img/rule134_1.png')},
      {name:'rule134_2.png',image:require('../assets/img/rule134_2.png')},
      {name:'rule134_3.png',image:require('../assets/img/rule134_3.png')},
      {name:'rule135_1.png',image:require('../assets/img/rule135_1.png')},
      {name:'rule135_2.png',image:require('../assets/img/rule135_2.png')},
      {name:'rule136.png',image:require('../assets/img/rule136.png')},
      {name:'rule137_1.png',image:require('../assets/img/rule137_1.png')},
      {name:'rule137_2.png',image:require('../assets/img/rule137_2.png')},
      {name:'rule138_1.png',image:require('../assets/img/rule138_1.png')},
      {name:'rule138_2.png',image:require('../assets/img/rule138_2.png')},
      {name:'rule138_3.png',image:require('../assets/img/rule138_3.png')},
      {name:'rule138_4.png',image:require('../assets/img/rule138_4.png')},
      {name:'rule139_1.png',image:require('../assets/img/rule139_1.png')},
      {name:'rule139_2.png',image:require('../assets/img/rule139_2.png')},
      {name:'rule139_3.png',image:require('../assets/img/rule139_3.png')},
      {name:'rule139_4.png',image:require('../assets/img/rule139_4.png')},
      {name:'rule140_1.png',image:require('../assets/img/rule140_1.png')},
      {name:'rule140_2.png',image:require('../assets/img/rule140_2.png')},
      {name:'rule141_1.png',image:require('../assets/img/rule141_1.png')},
      {name:'rule141_2.png',image:require('../assets/img/rule141_2.png')},
      {name:'rule141_3.png',image:require('../assets/img/rule141_3.png')},
      {name:'rule141_4.png',image:require('../assets/img/rule141_4.png')},
      {name:'rule142_1.png',image:require('../assets/img/rule142_1.png')},
      {name:'rule142_2.png',image:require('../assets/img/rule142_2.png')},
      {name:'rule142_3.png',image:require('../assets/img/rule142_3.png')},
      {name:'rule142_4.png',image:require('../assets/img/rule142_4.png')},
      {name:'rule143.png',image:require('../assets/img/rule143.png')},
      {name:'rule144.png',image:require('../assets/img/rule144.png')},
      {name:'rule145_1.png',image:require('../assets/img/rule145_1.png')},
      {name:'rule145_2.png',image:require('../assets/img/rule145_2.png')},
      {name:'rule146.png',image:require('../assets/img/rule146.png')},
      {name:'rule147.png',image:require('../assets/img/rule147.png')},
      {name:'rule148.png',image:require('../assets/img/rule148.png')},
      {name:'rule149.png',image:require('../assets/img/rule149.png')},
      {name:'rule150.png',image:require('../assets/img/rule150.png')},
      {name:'rule151.png',image:require('../assets/img/rule151.png')},
      {name:'rule152.png',image:require('../assets/img/rule152.png')},
      {name:'rule153.png',image:require('../assets/img/rule153.png')},
      {name:'rule154.png',image:require('../assets/img/rule154.png')},
      {name:'rule155.png',image:require('../assets/img/rule155.png')},
      {name:'rule156.png',image:require('../assets/img/rule156.png')},
      {name:'rule158_1.png',image:require('../assets/img/rule158_1.png')},
      {name:'rule158_2.png',image:require('../assets/img/rule158_2.png')},
      {name:'rule161.png',image:require('../assets/img/rule161.png')},
      {name:'rule163.png',image:require('../assets/img/rule163.png')},
      {name:'rule164_1.png',image:require('../assets/img/rule164_1.png')},
      {name:'rule164_2.png',image:require('../assets/img/rule164_2.png')},
      {name:'rule164_3.png',image:require('../assets/img/rule164_3.png')},
      {name:'rule164_4.png',image:require('../assets/img/rule164_4.png')},
      {name:'rule164_5.png',image:require('../assets/img/rule164_5.png')},
      {name:'rule168.png',image:require('../assets/img/rule168.png')},
      {name:'rule173_1.png',image:require('../assets/img/rule173_1.png')},
      {name:'rule173_2.png',image:require('../assets/img/rule173_2.png')},
      {name:'rule173_3.png',image:require('../assets/img/rule173_3.png')},
      {name:'rule173_4.png',image:require('../assets/img/rule173_4.png')},
      {name:'rule173_5.png',image:require('../assets/img/rule173_5.png')},
      {name:'rule173_6.png',image:require('../assets/img/rule173_6.png')},
      {name:'rule173_7.png',image:require('../assets/img/rule173_7.png')},
      {name:'rule177.png',image:require('../assets/img/rule177.png')},
      {name:'rule179_1.png',image:require('../assets/img/rule179_1.png')},
      {name:'rule179_2.png',image:require('../assets/img/rule179_2.png')},
      {name:'rule181_1.png',image:require('../assets/img/rule181_1.png')},
      {name:'rule181_2.png',image:require('../assets/img/rule181_2.png')},
      {name:'rule181_3.png',image:require('../assets/img/rule181_3.png')},
      {name:'rule183_1.png',image:require('../assets/img/rule183_1.png')},
      {name:'rule183_2.png',image:require('../assets/img/rule183_2.png')},
      {name:'rule184.png',image:require('../assets/img/rule184.png')},
      {name:'rule185_1.png',image:require('../assets/img/rule185_1.png')},
      {name:'rule185_2.png',image:require('../assets/img/rule185_2.png')},
      {name:'rule185_3.png',image:require('../assets/img/rule185_3.png')},
      {name:'rule187.png',image:require('../assets/img/rule187.png')},
      {name:'rule188.png',image:require('../assets/img/rule188.png')},


      {name:'aboutUs.jpg',image:require('../assets/img/aboutUs.jpg')},
      {name:'contactUs.jpg',image:require('../assets/img/contactUs.jpg')},
      {name:'downloadPdf.jpg',image:require('../assets/img/downloadPdf.jpg')},
      {name:'termsAndConditions.jpg',image:require('../assets/img/termsAndConditions.jpg')},

      
    ];
   
  
    static GetImage = (name) => {
      const found = ImageList.images.find(e => e.name === name);
      return found ? found.image : require('../assets/imageNotAvailable.png');
    };
  }